name: GitHub Release
on:
  push:
    tags: 
      - 'v*.*.*'
jobs:
  package-and-publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.

    # - name: Archive Release
    #   uses: thedoctor0/zip-release@0.7.1
    #   with:
    #     type: 'zip'
    #     filename: 'tnt.zip'
    #     path: './assets/a-framework'

    # 创建一个版本文件，用作检测更新
    - uses: "finnp/create-file-action@master"
      env:
        FILE_NAME: "./assets/a-framework/tnt-version.json"
        FILE_DATA: "{ \"version\": \"${{ github.ref_name }}\" }"

    - name: Install Zip
      uses: montudor/action-zip@v1

    - name: Zip output
      run: zip -r tnt.zip a-framework a-framework.meta preload-tnt.js preload-tnt.js.meta tnt-version.json
      working-directory: ./assets  

    - name: Release  
      uses: softprops/action-gh-release@v1
      with:
        files: ./assets/tnt.zip
        token: ${{ secrets.TNT_TOKEN }}